### ISSUE TITLE
Make without use of API Key.

### ISSUE THREAD

**Issue by haseeb-heaven** [ricklamers/gpt-code-ui#1]
```
Hi
I generated the following code:
Error: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

This should work without Key, You can use Javascript to do same thing in ChatGPT Website itself.
I was looking forward to it to use ChatGPT Website and not external API.

**Comment by ricklamers** [comment]
Sorry your own API key is required for accessing the OpenAI models

**Comment by bobwatcherx** [comment]
i have created .env file and its content as this

OPENAI_API_KEY=sk-PRIVATE

and i have filled my own apikey .  but getting error

I generated the following code:

```
Error: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

**Comment by haseeb-heaven** [comment]
Sorry but check the Chathub they have an option to use ChatGpt and Bard,bing AI with web interface you just need to login into websites thats it, No API key required
