### ISSUE TITLE
Codespaces with iOS mobile support

### ISSUE THREAD

**Issue by tapestreamer** [ricklamers/gpt-code-ui#11]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

Open this repo in codespaces and Start gptcode in terminal and open browser url to port 8080.

### Current behaviour

When I start “gptcode” I get a popup and it’s blank. Then opening port 8080 shows url unavailable. This is on IOS with Chrome.

### Steps to reproduce

Opened codespaces
Start “gptcode” in terminal
Get warning browser wants to open port 8080 and shows a popup-block warning in Chrome.
Opening the popup shows about:blank
When opening the port 8080 in codespaces it shows Url unavailable.

### Which Operating Systems are you using?

- [ ] Android
- [X] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Programming Version

Python

### gpt-code-ui Version

v0.42.16

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by coderFrankenstain** [comment]
because it listen on localhost ，This is a loopback address

**Comment by ricklamers** [comment]
I made some progress to get the devcontainer configured properly but because of the port forwarding and the app running on two local ports and some hardcoded paths running from Codespaces requires some more changes.

**Comment by ricklamers** [comment]
I added a Flask proxy to make the whole thing run on one port, it should now work in Codespaces (verified on my end).
