### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by derekcheungsa** [ricklamers/gpt-code-ui#12]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

Hi Rick,

Thanks for sharing your code!  I'm eager to use it.  After installing and uploading a file, I get this error

ModuleNotFoundError: No module named 'pandas'

### Current behaviour

![image](https://github.com/ricklamers/gpt-code-ui/assets/122410431/1de680ca-e4c0-46d6-8ba9-1e28dedfc266)

### Steps to reproduce

Install and run.  Uploaded a csv file.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Programming Version

python 3.10

### gpt-code-ui Version

Open Source - v0.42.17

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by derekcheungsa** [comment]
Sorry, figured it out.  I just needed to install that in my environment.  It inherits the python packages that I've previously insta..ed

**Comment by ricklamers** [comment]
One feature idea is to autodetect the packages that are included in the generated code and match them against the `pip` installed packages: https://github.com/ricklamers/gpt-code-ui/discussions/6.

Glad you figured this out though!
