### ISSUE TITLE
not read the whole csv file

### ISSUE THREAD

**Issue by niyeyedi110** [ricklamers/gpt-code-ui#14]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

I open a csv file,and want the project display all the data,but it just display some of the data as followings.

### Current behaviour

![image](https://github.com/ricklamers/gpt-code-ui/assets/79386975/12288efa-3196-414c-bc74-cb3aae53f626)
open the file
I generated the following code:
import pandas as pd

data = pd.read_csv("111.csv")
data.head()
     1  Unnamed: 1
0  2.0         NaN
1  3.0         NaN
2  NaN         NaN
3  NaN         NaN
4  5.0         NaN

### Steps to reproduce

display all the data

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Programming Version

Python 3.10

### gpt-code-ui Version

Open Source - v0.42.19

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ricklamers** [comment]
Hi @niyeyedi110. By default .head() from Pandas shows the first 5 rows. See the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html).

You could be more specific in your message and ask it to print all rows and it'll probably be smart enough to not use head().
