### ISSUE TITLE
Failling to use GPT-4 model

### ISSUE THREAD

**Issue by braibaud** [ricklamers/gpt-code-ui#16]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

It should work with both gpt-3.5 and gpt.4 seamlessly 

### Current behaviour

Whenever the GPT-4 model is selected, it reports an issue "model does not exist" (same thing happens with v0.42.29):

<img width="1213" alt="image" src="https://github.com/ricklamers/gpt-code-ui/assets/3780064/555fda46-70c9-4029-9151-4a483887d846">

```
Error: {
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```

### Steps to reproduce

1. start the app
2. select model gpt-4
3. do anything
4. it fails

### Possible solution

tbd

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Programming Version

Python 3.10

### gpt-code-ui Version

v0.42.29

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ricklamers** [comment]
You might need to get API access https://openai.com/waitlist/gpt-4-api
