### ISSUE TITLE
[Enhancement] Describe the Misc. part of the README.md better

### ISSUE THREAD

**Issue by AkhilProto** [ricklamers/gpt-code-ui#24]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/ricklamers/gpt-code-ui/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/ricklamers/gpt-code-ui/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

We should update the Misc. part of the README.md file so that the new users can easily understand that part and have a hassle-free experience of the project. 

### ✔️ Solution

Most of the users don't know that we cannot see the ```.env``` file even if there is one already in the directory.(Reason - It is a hidden file as it has no name and only an extension.) I have recently faced this issue where it was to asking me whether it should replace the existing ```.env``` file with the new one i was trying to add.

So my Enhancement Idea is to update the Misc. Section of the README.md file so that the user who is trying to install, whether be a skilled programmer or not, can easily understand it and have a better experience of the **gpt-code-ui**.

### ❓ Alternatives

I haven't considered any other alternatives. But you might think that the ```.env``` file is mainly used for entering the  OPENAI_API_KEY and that can be done in the Web UI also, but the problem here is that the user will then be left puzzled about what to do with the Misc. part of the repository.

### 📝 Additional Context

By assigning me to this issue, i will be creating the pull request in less than 2 days.
I would add the commands for Windows, Linux, and  MacOS(if possible).

_No response_

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ricklamers** [comment]
Please see https://github.com/ricklamers/gpt-code-ui/pull/25
