### ISSUE TITLE
python files crashes

### ISSUE THREAD

**Issue by 0day404** [ricklamers/gpt-code-ui#34]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

 It worked before, but now it won't open，Running all python files crashes，not available

### Current behaviour

<
<img width="867" alt="屏幕截图 2023-06-06 175926" src="https://github.com/ricklamers/gpt-code-ui/assets/128878325/efacb4c2-5387-4967-b6ac-fccca1f7a837">

### Steps to reproduce

Unable to open, running all python files crashes

### Possible solution

I reinstalled latest python，I set utf-8

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Programming Version

ptthon 3.11

### gpt-code-ui Version

v0.42.29

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ricklamers** [comment]
This looks like an issue with your Python installation. I’d recommend a clean install using the Windows Python installer and the `pip` installation method.

**Comment by KayCHENvip** [comment]
This is indeed the case, I found that my computer cannot execute pip, I am solving the problem, thank you very ***@***.***
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Rick ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/6/2023 19:13
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            chen ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [ricklamers/gpt-code-ui] python files crashes (Issue #34)
        
      
    
  

This looks like an issue with your Python installation. I’d recommend a clean install using the Windows Python installer and the pip installation method.

**Comment by KayCHENvip** [comment]
> 这看起来像是您的 Python 安装的问题。我建议使用 Windows Python 安装程序和`pip`安装方法进行全新安装。

Now, my python and pip are correct, but running all python files still crashes and is unavailable
