### ISSUE TITLE
Proper contributors guide

### ISSUE THREAD

**Issue by swyxio** [ricklamers/gpt-code-ui#37]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/ricklamers/gpt-code-ui/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/ricklamers/gpt-code-ui/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

i got this running locally, using a `make build` and then running `python gpt-code-ui/main.py`, but when i change the frontend, nothing updates on the localhost:8080 site. 

your contirbuting link points to this
https://github.com/ricklamers/gpt-code-ui/blob/main/.github/CONTRIBUTING.md

which offers no real guidance on frontend/backend local dev. help?

### ✔️ Solution

i'd like some hints as to how to modify locally

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by swyxio** [comment]
note to self:

- having gpt-code-ui pip installed interferes with the project. need to uninstall it
- make a virtual env
- `pip install -e .`

**Comment by swyxio** [comment]
update - the modifying frontend part doesnt seem to work. revert to just `make compile_frontend` and then `python gpt_code_ui/main.py`. no live reload

**Comment by ricklamers** [comment]
I can see how it's not straightforward without digging into the code how to run the frontend in development mode, added instructions: https://github.com/ricklamers/gpt-code-ui/blob/main/.github/CONTRIBUTING.md#getting-started
