### ISSUE TITLE
Uploading CSV file fails to load

### ISSUE THREAD

**Issue by grexzen** [ricklamers/gpt-code-ui#40]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

Upload csv file, ask for head, bot prints code results.

### Current behaviour

Upload file, ask for head, spins, nothing. 

### Steps to reproduce

See above.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Programming Version

Python 3.10

### gpt-code-ui Version

Latest

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ricklamers** [comment]
![IMG_0606](https://github.com/ricklamers/gpt-code-ui/assets/1309307/d73f4499-a915-49b9-b7b4-5e02c653ed1b)

Works fine for me. Please add some more details and re-open if needed.
