### ISSUE TITLE
multi-session support

### ISSUE THREAD

**Issue by pycui** [ricklamers/gpt-code-ui#41]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/ricklamers/gpt-code-ui/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/ricklamers/gpt-code-ui/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Right now there can only be one active session. If I open more tabs/pages, the interactions just got mixed up in the conversation. This also prevent it being deployable as a service. 

Wondering if there is plan to support this. If there is no plan but you can show me the best place to add this I'm happy to contribute too. 

### ✔️ Solution

Support multi-session. 

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ricklamers** [comment]
Correct, this is currently not supported. I welcome a PR but won't be able to dedicate the time to develop it.
