### ISSUE TITLE
如果生成的脚本代码，在本地执行时存在错误，应用会一直卡在Running code环节

### ISSUE THREAD

**Issue by linghongli** [ricklamers/gpt-code-ui#49]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

如果GPT生成的脚本，在本地执行时，有错误，应该是GPT重新生成正确的脚本，并继续往下执行，直至最终正确执行

### Current behaviour

如果GPT生成的python script，在本地执行过程中存在一些错误，应用并不会让GPT重新生成正确的应用，并进行下一步的动作，而一直开在本地执行代码的环节中

![22](https://github.com/ricklamers/gpt-code-ui/assets/2770205/d941f013-4c87-4227-97d1-c66f661a13c8)

将代码放到本地，手动执行测试（发现脚本有异常）
![33](https://github.com/ricklamers/gpt-code-ui/assets/2770205/b886b8c7-9ec8-4df2-9e15-4604b0a492bf)

### Steps to reproduce

如果GPT生成的python script，在本地执行过程中存在一些错误，应用并不会让GPT重新生成正确的应用，并进行下一步的动作，而一直开在本地执行代码的环节中

![22](https://github.com/ricklamers/gpt-code-ui/assets/2770205/d941f013-4c87-4227-97d1-c66f661a13c8)

将代码放到本地，手动执行测试（发现脚本有异常）
![33](https://github.com/ricklamers/gpt-code-ui/assets/2770205/b886b8c7-9ec8-4df2-9e15-4604b0a492bf)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Programming Version

python v3.8

### gpt-code-ui Version

v0.42.32

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ricklamers** [comment]
Sorry, English only please
