### ISSUE TITLE
[Feature Request] Azure OpenAI support

### ISSUE THREAD

**Issue by tiangao88** [ricklamers/gpt-code-ui#5]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/ricklamers/gpt-code-ui/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/ricklamers/gpt-code-ui/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Can you please support Azure OpenAI thanks to a proxy solution such as https://github.com/haibbo/cf-openai-azure-proxy/blob/main/README_en.md

### ✔️ Solution

There could be an .env variable such as OPENAI_BASE_URL so we can replace api.openai.com with my-azure-oai-proxy.mydomain.com in the code below

    response = requests.post(
        "https://api.openai.com/v1/chat/completions",
        data=json.dumps(data),
        headers=headers,
    )

Thanks!

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ricklamers** [comment]
Good idea! 

`OPENAI_BASE_URL` is now picked up from v0.42.16
