### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by guranu** [ricklamers/gpt-code-ui#60]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

For it to install fine

### Current behaviour

[log termux.txt](https://github.com/ricklamers/gpt-code-ui/files/12138428/log.termux.txt)

### Steps to reproduce

pip install gpt-code-ui

### Possible solution

By updating numpy from 1.24 to 1.25.1 and updating pandas from 1.5 to 2.0.3

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Programming Version

Python 3.11.4

### gpt-code-ui Version

v0.42.35

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by romanovj** [comment]
In order to builf numpy with clang you should pass aditional flags
CFLAGS+=" -U__ANDROID_API__ -D__ANDROID_API__=33" MATHLIB=m pip install

**Comment by guranu** [comment]
Thanks it worked but i can't seem build pyzmq any way to fix this problem?

**Comment by guranu** [comment]
Now i get this error when i try to launch it: Traceback (most recent call last):                        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 285, in <module>     set_scputimes_ntuple("/proc")                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 432, in wrapper       raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^                           File "<string>", line 3, in raise_from                  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 430, in wrapper       ret = cache[key] = fun(*args, **kwargs)                                    ^^^^^^^^^^^^^^^^^^^^               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 268, in set_scputimes_ntuple                                                 with open_binary('%s/stat' % procfs_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^             File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 765, in open_binary                                                           return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                   PermissionError: [Errno 13] Permission denied: '/proc/stat'
0.00s - Debugger warning: It seems that frozen modules are being used, which may                                0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off                                    0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.          cd                                                      ^CTerminating processes...
Cleaning up kernels...
Processes terminated.
~ $ cd /data/data/com.termux/usr
bash: cd: /data/data/com.termux/usr: No such file or directory

**Comment by ricklamers** [comment]
AFAICT I’m not directly depending on psutil and the stack trace doesn’t reveal where psutil is being called. This might be done by ipykernel. Android has removed access to process information by blocking access to /proc/stat (eg see https://github.com/termux/termux-app/issues/299)

I don’t plan to explicitly support Android but if a hacker wants to make it work I’d welcome a patch or workaround that will get rid of the psutil dependency.

**Comment by ricklamers** [comment]
https://github.com/ipython/ipykernel/blob/58e9d150acb661c9e9440c1d011edb840eb510d1/ipykernel/kernelbase.py#L83

psutil use in ipykernel

**Comment by ricklamers** [comment]
I’ve seen https://github.com/termux/proot-distro referenced as a way to get ipykernel to work without requiring root access (which is typically only possible with jailbreaks and generally not recommended because of the risks)

**Comment by romanovj** [comment]
@guranu you can acess /proc/stat with adb shell rights

so all you need is to rewrite some code like here
https://community.home-assistant.io/t/home-assistant-core-on-android-tablet/250174/178?u=romanovj
