### ISSUE TITLE
integrate with database like MySQL's query result

### ISSUE THREAD

**Issue by huqianghui** [ricklamers/gpt-code-ui#80]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/ricklamers/gpt-code-ui/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/ricklamers/gpt-code-ui/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Right now, the project only support the uploaded datasource.
Is there possible to translate user's language to SQL by codex model, then query the result as datasource to do data analysis and visualization?

### ✔️ Solution

Because the data source just supports the uploaded files.

And I want to use different datasources like database as data sources.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ricklamers** [comment]
You should be able to ask it to connect to a database. You will need to provide a database connection string. Dedicated support for something like this I consider to be outside of the scope of the project, I want to keep it simple.
